import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Walcart Landing Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/walcart-logo.png" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
					integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
					crossorigin="anonymous"
					referrerpolicy="no-referrer"
				/>
			</Head>

			<main>
				<h1>Walcart Landing Page</h1>
			</main>

			<footer></footer>
		</div>
	);
}
