import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Walcart Landing Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/walcart-logo.png" />
			</Head>
      

			<main>
				<h1>Walcart Landing Page</h1>
			</main>

			<footer></footer>
		</div>
	);
}
